name: Build

on: 
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
      
jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.runs-on }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        config:            
          - name: Windows 64
            runs-on: windows-latest
            build-mode: SIMBA_WIN64
            binary: Simba-Win64.exe
            test: Simba-Win64.exe
            
          - name: Windows 32  
            runs-on: windows-latest
            build-mode: SIMBA_WIN32
            binary: Simba-Win32.exe
            test: Simba-Win32.exe

          - name: Linux 64
            runs-on: ubuntu-latest
            build-mode: SIMBA_LINUX64
            binary: Simba-Linux64
            test: Simba-Linux64
          
          - name: AArch64  
            runs-on: ubuntu-latest
            build-mode: SIMBA_AARCH64
            binary: Simba-AArch64
            
          - name: MacOS 64
            runs-on: macos-latest
            build-mode: SIMBA_DARWIN64
            binary: Simba-Darwin64.zip
            test: Simba-Darwin64
            
    steps:
      - uses: actions/checkout@v2.4.0
        with: 
          submodules: true
      
      - name: Install Lazarus
        uses: ollydev/setup-lazarus-fpcup@v2.5
        with:
          laz-branch: lazarus_2_2_0
          fpc-branch: release_3_2_2
          fpcup-release: v2.2.0h
    
      - name: Build Simba
        run: |
          export GITHUB_SHORT_SHA=$(git rev-parse --short HEAD)
          
          lazbuild --build-mode=${{ matrix.config.build-mode }} "Source/Simba/Simba.lpi"

      - name: Test Simba
        if: matrix.config.test != ''
        run: |
          if [ "${{ matrix.config.runs-on }}" = "ubuntu-latest" ]; then
              export DISPLAY=:1
              Xvfb :1 & sleep 2
          fi
          if [ "${{ matrix.config.runs-on }}" != "windows-latest" ]; then
              chmod +x ${{ matrix.config.test }}
          fi
          
          ./${{ matrix.config.test }} --silent --run "Tests/simba"

      - name: Upload Binary 
        uses: actions/upload-artifact@v2.3.1
        with:
          name: ${{ matrix.config.binary }}
          path: ${{ matrix.config.binary }}