name: docs

on:
  workflow_run:
    workflows:
      - build
    types:
      - completed

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true      

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: windows-latest
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' && github.event.workflow_run.head_repository.full_name == 'Villavu/Simba' && github.event.workflow_run.head_branch == 'simba2000'
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          ref: ${{ github.event.workflow_run.head_branch }}      

      - name: Build files
        shell: bash
        run: |
          pip3 install sphinx furo myst-parser
          cd DocGen
          python3 docgen.py

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: DocGen/build/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4